### ISSUE TITLE
"sdwan_centralized_policy" not supporting fully "sdwan_custom_control_topology_policy_definition"| Provider not accepting all valid parameters

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#113]
Look at the below sample of creating a "sdwan_centralized_policy" containing "sdwan_custom_control_topology_policy_definition"

when the type is "control", we should be able to provide the entries as 2 values

1. direction. The direction should either be in or out.
2. Site List or Region List or Region id

however, in the documentation of resource "sdwan_centralized_policy", the only allowed values for the direction are **service, tunnel, all**
The only allowed 2nd filter is site List, it is not allowing Region List and region Id.

The Priority is to fix the direction issue first, as it would allow us to go ahead with creating policy with Site List.
The remaining can be done after this is done.

sample with Site list
```yaml
policyDescription: tetst
policyType: feature
policyName: TEST
policyDefinition:
  assembly:
    - definitionId: 9f34b477-596e-4cd4-a1a9-671feb754e6a
      type: control
      entries:
        - direction: in
          siteLists:
            - 987a33b2-8963-4310-af8b-66ee51c2298b
            - b0e2c185-e7eb-492d-9c0e-f8f95927d468
        - direction: out
          siteLists:
            - 04a26f02-07de-45fe-8302-e099ee12f2fa
            - e16239f4-f3db-4846-865d-ed0d30deb692
  regionRoleAssembly: []
isPolicyActivated: false

```
sample with region id
```yaml
policyDescription: wqde
policyType: feature
policyName: s
policyDefinition:
  assembly:
    - definitionId: 7e71364b-d6bb-41a6-8770-4b46c1f68cc6
      type: control
      entries:
        - direction: in
          regionIds:
            - '4'
        - direction: out
          regionIds:
            - '5'
  regionRoleAssembly: []
isPolicyActivated: false
```

<img width="313" alt="image" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/8275b8ba-1719-43de-b619-1af853ec6050">

<img width="1256" alt="image" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/cd39cd46-c08a-45e7-9c27-bad73a480be4">
