### ISSUE TITLE
Bug after upgrade | sdwan_hub_and_spoke_topology_policy_definition

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#230]
After updating the provider to latest, getting the below error for sdwan_hub_and_spoke_topology_policy_definition

╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for
│ module.sdwan.sdwan_hub_and_spoke_topology_policy_definition.hub_and_spoke_topology_policy_definition["HST_DEFINITION_T1-rrahimm"].type. All
│ values must be known after apply, so this is always a bug in the provider and should be reported in the provider's own repository. Terraform
│ will still save the other known object values in the state.

Running version

<img width="285" alt="image" src="https://github.com/CiscoDevNet/terraform-provider-sdwan/assets/39684933/e8e054b4-b917-40c2-8c69-2956cd960476">

**Comment by rrahimm** [comment]
Happening when using the below commented fields, that were added as part of https://github.com/CiscoDevNet/terraform-provider-sdwan/issues/112

   ```
     hub_and_spoke_topology:
          - name: HST_DEFINITION_T1-rrahimm
            description: HST_DEFINITION_T1-rrahimm
            vpn_list: VPN-LIST-HST-T1-rrahimm
            hub_and_spoke_sites:
              - name: group1
                spokes:
                  - site_list: CALIFORNIA-HST-T-rrahimm
                    hubs:
                      - site_list: BOSTON-HST-T-rrahimm
                      - site_list: NEWYORK-HST-T-rrahimm
                        # ipv4_prefix_lists:
                        #   - PREFIX-LIST-HST-T-rrahimm
              - name: group2
                equal_preference: true
                # advertise_tloc: true
                # tloc_list: TLOC-LIST-HST-T2-rrahimm
                spokes:
                  - site_list: WASHINGTON-HST-T-rrahimm
                    hubs:
                      - site_list: KENTUCKY-HST-T-rrahimm
          - name: HST_DEFINITION_T2-rrahimm
            description: HST_DEFINITION_T2-rrahimm
            vpn_list: VPN-LIST-HST-T1-rrahimm
            hub_and_spoke_sites:
              - name: group1
                equal_preference: true
                # advertise_tloc: true
                # tloc_list: TLOC-LIST-HST-T1-rrahimm
                spokes:
                  - site_list: DENVER-CCT-T-rrahimm
                    hubs:
                      - site_list: ATLANTA-CCT-T-rrahimm
                        # ipv4_prefix_lists:
                        #   - PREFIX-LIST-HST-T-rrahimm
```
