### ISSUE TITLE
sdwan_centralized_policy | API payload order being sorted (Urgent)

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#272]
we see a different behaviour just with resource sdwan_centralized_policy

In most TF providers we will see that the API will use the payload in the same order we handle them in the Terraform Module
but in this one, it is trying to do some sorting

For example, the Data Input is

```
    traffic_data:
          - policy_definition: TD_DEFINITION_T1-rrahimm
            site_region_vpn:
              - direction: service
                region_list: RL-CORE-rrahimm
                vpn_lists:
                  - VPN-LIST-TD-T2-rrahimm
              - direction: tunnel
                region_list: RL-CORE-rrahimm
                vpn_lists:
                  - VPN-LIST-TD-T2-rrahimm
              - direction: all
                region_list: RL-GLOBAL-rrahimm
                vpn_lists:
                  - VPN-LIST-TD-T1-rrahimm
                  - VPN-LIST-TD-T2-rrahimm 
```

but the Terraform plan looks like this

```
# module.sdwan.sdwan_centralized_policy.centralized_policy["Super_policy_T2-rrahimm"] will be updated in-place
  ~ resource "sdwan_centralized_policy" "centralized_policy" {
      ~ definitions = [
          + {
              + entries = [
                  + {
                      + direction            = "all"
                      + region_list_ids      = [
                          + "bef11466-f66f-49b8-babc-04e1ab24d22b",
                        ]
                      + region_list_versions = [
                          + "0",
                        ]
                      + vpn_list_ids         = [
                          + "0d27c30d-4f02-4dae-bf4b-56f3783ba79f",
                          + "b6f43b71-490b-4628-9bc2-66c7948e1841",
                        ]
                      + vpn_list_versions    = [
                          + "0",
                          + "0",
                        ]
                    },
                  + {
                      + direction            = "service"
                      + region_list_ids      = [
                          + "1463ddbb-4f16-408e-8616-f66d3a445f83",
                        ]
                      + region_list_versions = [
                          + "0",
                        ]
                      + vpn_list_ids         = [
                          + "0d27c30d-4f02-4dae-bf4b-56f3783ba79f",
                        ]
                      + vpn_list_versions    = [
                          + "0",
                        ]
                    },
                  + {
                      + direction            = "tunnel"
                      + region_list_ids      = [
                          + "1463ddbb-4f16-408e-8616-f66d3a445f83",
                        ]
                      + region_list_versions = [
                          + "0",
                        ]
                      + vpn_list_ids         = [
                          + "0d27c30d-4f02-4dae-bf4b-56f3783ba79f",
                        ]
                      + vpn_list_versions    = [
                          + "0",
                        ]
                    },
                ]
              + id      = "88cfa137-9de6-4feb-a3eb-ab1c1b2ded23"
              + type    = "data"
              + version = 37
            },
            # (2 unchanged elements hidden)
        ]
        id          = "54c7b134-ad1f-4291-9cf9-526250f9e620"
        name        = "Super_policy_T2-rrahimm"
      ~ version     = 7 -> (known after apply)
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
module.sdwan.sdwan_centralized_policy.centralized_policy["Super_policy_T2-rrahimm"]: Modifying... [id=54c7b134-ad1f-4291-9cf9-526250f9e620]
module.sdwan.sdwan_centralized_policy.centralized_policy["Super_policy_T2-rrahimm"]: Modifications complete after 6s [id=54c7b134-ad1f-4291-9cf9-526250f9e620]
```

as you can see above, in our YAML the direction order is service, tunnel and then all
but TF provider make it all, service and tunnel

i confirmed our TF Module is not doing this order swapping. Is this something done on purpose in TF Provider
https://github.com/netascode/terraform-sdwan-nac-sdwan/blob/main/sdwan_centralized_policies.tf

The order swapping seems not a requirement of the SDWAN configurations, as the GUI allows them to be put in any order.
