### ISSUE TITLE
Security Policies | Mode: Unified | Doesn't support all parameters

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#395]
We were trying to use the different resources under the **(Classic) Security Policies** in the provider, with mode set to unified.

On further analysis we found that, the feature possible didn't include all sub-options that are part of the mode=unified, though it has everything for mode=security.

For example,
The current provider for [security_policy](https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/security_policy), only supports Legacy Security Policy.

The Unified Security Policy is a bit different and is here in the Web UI **Configuration >> Security >> Add Unified Security Policy**

Some notable differences include, the USP should allow adding srcZoneListId and dstZoneListId along with each of the definitionId for zoneBasedFW.

Sample payload below, as seen from WEB UI inspector.

```yaml
{
    "policyName": "USP_1",
    "policyDescription": "USP_1",
    "policyMode": "unified",
    "policyDefinition": {
        "assembly": [
            {
                "definitionId": "0d235015-2ce5-4481-8b3d-b3176246b244",
                "type": "advancedInspectionProfile"
            },
            {
                "definitionId": "4ad4a035-82c5-454d-8c81-bab6271d64c1",
                "type": "DNSSecurity"
            },
            {
                "definitionId": "8cee86ce-9419-4e12-ae9f-3dae739b8fc2",
                "type": "zoneBasedFW",
                "entries": [
                    {
                        "srcZoneListId": "35a4ba42-245f-438f-bf74-6590186b0227",
                        "dstZoneListId": "184bf81d-5147-4548-8bdc-117fff85b06c"
                    }
                ]
            }
        ],
        "settings": {
            "tcpSynFloodLimit": "1024",
            "maxIncompleteTcpLimit": "1024",
            "maxIncompleteUdpLimit": "1025",
            "maxIncompleteIcmpLimit": "1026",
            "highSpeedLogging": {
                "serverIp": "2.3.4.5",
                "vrf": "2",
                "port": "2055"
            },
            "auditTrail": "on",
            "unifiedLogging": "on",
            "sessionReclassifyAllow": "on",
            "icmpUnreachableAllow": "on",
            "logging": [
                {
                    "vpn": "1",
                    "serverIP": "2.3.5.6"
                }
            ],
            "failureMode": "open"
        }
    }
    "policyType": "feature",
    "policyUseCase": "custom",
    "policyContainsUtd": true,
    "policyContainsTls": true
}
```

Please expose all capabilities of the **(Classic) Security Policies** in the provider, when mode is set to unified.

**Please review all the resources below and see if they support mode=unified""

<img width="312" alt="Image" src="https://github.com/user-attachments/assets/9f6cf784-762b-47d9-a610-d02622538d0c" />

Priority is to fix this on the below 2

https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/zone_based_firewall_policy_definition

https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/resources/security_policy
