### ISSUE TITLE
sdwan_attach_feature_device_template | detach operation failure

### ISSUE THREAD

**Issue by rrahimm** [CiscoDevNet/terraform-provider-sdwan#417]
when we use **sdwan_attach_feature_device_template** to detach a specific device from a device template, we see that all the devices attached with that **Device Template** is detached from the template rather than just the device we intended to detach.

For example, the following 2 devices are attached to device template **DT-DC-C8000V-01**

```
---
# SD-WAN Sites
sdwan:
  sites:
    - id: 100
      routers:
        - chassis_id: C8K-40C0CCFD-9EA8-2B2E-E73B-32C5924EC79B
          model: C8000V
          device_template: DT-DC-C8000V-01
          device_variables:
            site_id: 100
            system_ip: 10.0.0.1
            system_hostname: SD-DC-C8KV-01
            <truncated>
        - chassis_id: C8K-E94D7B88-4B9E-3323-C6C3-F29079FAAC3B
          model: C8000V
          device_template: DT-DC-C8000V-01
          device_variables:
            site_id: 100
            system_ip: 10.0.0.2
            system_hostname: SD-DC-C8KV-02
            <truncated>
```
vManage showing device attachment to template

<img width="1598" alt="Image" src="https://github.com/user-attachments/assets/53c3d42c-85cd-455b-a3bc-e0b545c67175" />

Now, we want to detach device **C8K-E94D7B88-4B9E-3323-C6C3-F29079FAAC3B** from Device Template **DT-DC-C8000V-01**

```
---
# SD-WAN Sites
sdwan:
  sites:
    - id: 100
      routers:
        - chassis_id: C8K-40C0CCFD-9EA8-2B2E-E73B-32C5924EC79B
          model: C8000V
          device_template: DT-DC-C8000V-01
          device_variables:
            site_id: 100
            system_ip: 10.0.0.1
            system_hostname: SD-DC-C8KV-01
            <truncated>
```

Now the Terraform Plan is also just confirming, that only one device will be detached from Device template

```
 # module.sdwan.sdwan_attach_feature_device_template.attach_feature_device_template["C8K-E94D7B88-4B9E-3323-C6C3-F29079FAAC3B"] will be destroyed
  # (because key ["C8K-E94D7B88-4B9E-3323-C6C3-F29079FAAC3B"] is not in for_each map)
  - resource "sdwan_attach_feature_device_template" "attach_feature_device_template" {
      - devices = [
          - {
              - id        = "C8K-E94D7B88-4B9E-3323-C6C3-F29079FAAC3B" -> null
              - variables = {
                  - "controller_groups"                                = "1,2"
                  - "global_cdp_enable"                                = "true"
            	  <truncated>
                } -> null
            },
        ] -> null
      - id      = "50b663e5-8669-4a95-99a6-13bfe47d7a55" -> null
      - version = 0 -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.
```

However, we see that both the devices that were attached to the Device Template **DT-DC-C8000V-01** were detached. You can see below, both devices switched mode to **CLI**

<img width="1609" alt="Image" src="https://github.com/user-attachments/assets/b3eeb19a-2569-4214-bab3-74bc14e8bfe3" />

On debugging the Terraform provider calls, we are able to confirm that the Provider did ask the API to detach both devices from the template rather than just one.

```
2025-03-25T15:44:18.452+0530 [DEBUG] provider.terraform-provider-sdwan_v0.5.3: 2025/03/25 15:44:18 [DEBUG] HTTP Request: POST, https://198.18.1.100/dataservice/template/config/device/mode/cli, {{"deviceType":"vedge","devices":[{"deviceId":"C8K-40C0CCFD-9EA8-2B2E-E73B-32C5924EC79B","deviceIP":"10.0.0.1"},{"deviceId":"C8K-E94D7B88-4B9E-3323-C6C3-F29079FAAC3B","deviceIP":"10.0.0.2"}]}}
2025-03-25T15:44:19.246+0530 [DEBUG] provider.terraform-provider-sdwan_v0.5.3: 2025/03/25 15:44:19 [DEBUG] HTTP Response: {"id":"device_config_mode_cli-3ecf44f7-a7e4-45ea-b7f0-5050a18c7f7f"}
2025-03-25T15:44:19.246+0530 [DEBUG] provider.terraform-provider-sdwan_v0.5.3: 2025/03/25 15:44:19 [DEBUG] Exit from Do method
111
```
